version: '3.8'
services:
 csvserver:
    image: prom/prometheus:v2.22.0
    volumes:
      - "./inputFile:/csvserver/inputdata"
    ports:
      - "9393:9300"
   prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9300:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml


volumes:
  prometheus-data:
depends on:
   - csvserver
