
version: '3.3'

services:
 csvserver:
    image: infracloudio/csvserver:latest
    volumes:
      - "/root/csvserver/solution/inputFile:/csvserver/inputdata"
    ports:
      - "9393:9300"
    environment:
       CSVSERVER_BORDER: Orange
 prometheus:
    image: prom/prometheus:v2.22.0
    ports:
      - "9090:9090"
    depends_on:
      - csvserver
    volumes:
      - "/root/csvserver/solution/prometheus.yml:/etc/prometheus/prometheus.yml"
    depends_on:
      - csvserver

